env:
  browser: true
  es2021: true
extends:
  - plugin:vue/vue3-essential
  - standard-with-typescript
parser: vue-eslint-parser
parserOptions:
  ecmaVersion: latest
  sourceType: module
  parser: '@typescript-eslint/parser'
  extraFileExtensions:
    - vue
plugins:
  - vue
rules: {
  vue/multi-word-component-names: 'off'
}
